version: '3.8'

services:
  app:
    image: demo/laravel:0.1
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: sampole
      DB_USERNAME: root
      DB_PASSWORD: 
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: hello  # Set this to a secure password
      MYSQL_DATABASE: sampole
      # Remove MYSQL_USER and MYSQL_PASSWORD
    ports:
      - "3306:3306"
